spring.application.name=quizapp

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/quizapp}
spring.datasource.username=${DB_USERNAME:quizapp_user}
spring.datasource.password=${DB_PASSWORD:quizapp_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none

DB_ADMIN_USERNAME=quizapp_user
DB_ADMIN_PASSWORD=quizapp_password

spring.liquibase.user=quizapp_user
spring.liquibase.password=quizapp_password
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.liquibase.enabled=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=832399595299-is8tjvsm453p4v03jghappgm8p4rbltr.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile